services:
  test-moonshine-nginx:
    build:
      context: .
      dockerfile: ./docker/dockerfiles/nginx/Dockerfile
      target: dev
    container_name: ${COMPOSE_PROJECT_NAME}-nginx
    volumes:
      - ./:${APP_PATH}
    depends_on:
      - test-moonshine-php
    links:
      - test-moonshine-php:php
    networks:
      - traefik-docker
    labels:
        - "traefik.enable=true"
        - "traefik.docker.network=traefik-docker"
        - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.rule=Host(`moonshine-demo.docker.dev`)"
        - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.entrypoints=https"
        - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.tls=true"
        - "traefik.http.services.${COMPOSE_PROJECT_NAME}.loadbalancer.server.port=80"

  test-moonshine-php:
    build:
      args:
        user: ${DOCKER_USER}
        uid: 1000
        target: dev
      context: .
      dockerfile: ./docker/dockerfiles/php/Dockerfile
      target: dev
    container_name: ${COMPOSE_PROJECT_NAME}-php
    volumes:
      - ./:${APP_PATH}
    depends_on:
      - test-moonshine-db
      - test-moonshine-redis
    networks:
      - traefik-docker

  test-moonshine-db:
    container_name: ${COMPOSE_PROJECT_NAME}-db
    build:
      context: .
      dockerfile: ./docker/dockerfiles/mysql/Dockerfile
    volumes:
      - ./docker/volumes/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASS}
    networks:
      - traefik-docker

  test-moonshine-redis:
    container_name: ${COMPOSE_PROJECT_NAME}-redis
    image: redis:7.0.11-alpine
    volumes:
      - ./docker/volumes/redis:/data
    networks:
      - traefik-docker

  test-moonshine-npm:
    build:
      context: .
      dockerfile: ./docker/dockerfiles/node/Dockerfile
    container_name: ${COMPOSE_PROJECT_NAME}-npm
    volumes:
      - ./:${APP_PATH}:cached
      - ./.env:${APP_PATH}/.env
    working_dir: ${APP_PATH}
    profiles: ["npm"]
    entrypoint: ['npm']
    networks:
      - traefik-docker

networks:
  traefik-docker:
    external: true
